services:
  backend:
    build:
      context: ./simpleInvetoryApiBackend
    ports:
      - "1111:1111"
    environment:
      - PORT=1111
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./inventorydashboardfrontend
    ports:
      - "2222:2222"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:1111
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
